Areas/Administrator/Controllers/ThongKeController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace WatchShop.Areas.Administrator.Controllers
{
    public class ThongKeController : Controller
    {
        // GET: Administrator/ThongKe
        AdminDB aDB = new AdminDB();
        [HandleError]
        public ActionResult Index()
        {
            if (Session["accname"] == null)
            {
                Session["accname"] = null;
                return RedirectToAction("Login", "Account");
            }
            else
            {
                DateTime value = new DateTime();
                value = DateTime.Now;
                int mm = value.Month;
                int yy = value.Year;             
                ViewBag.DoanhThu = aDB.TinhDoanhThuNam().ToString("#,##0");
                ViewBag.HoaDonDangGiao = aDB.TinhSoHoaDonChuaGiao();
                ViewBag.HoaDonDaHoanTat = aDB.TinhSoHoaDonDaGiao();
                ViewBag.HoaDonChoXacNhan = aDB.TinhSoHDTrongNgay();
                ViewBag.HoaDonDaXacNhan = aDB.TinhSoHoaDonChuaHoanTat();
                ViewBag.SanPhamHetHang = aDB.SoSanPhamHetHang();
                ViewBag.NewCus = aDB.newCustomer();
                ViewBag.DoanhThuThangNam = aDB.TinhDoanhThuTheoThangNam(mm,yy).ToString("#,##0");
                return View();
            }          
        }
        [HandleError]
        public ActionResult DoanhThuThangNam()
        {

            if (Session["accname"] == null)
            {
                Session["accname"] = null;
                return RedirectToAction("Login", "Account");
            }
            else
            {
                DateTime value = new DateTime();
                value = DateTime.Now;
                int mm = value.Month;
                int yy = value.Year;          
                var model = aDB.LayHoaDonTheoThangNam(mm,yy);             
                return View(model);
            }
        }
        [HandleError]
        public ActionResult DoanhThuCacThang(string id)
        {

            if (Session["accname"] == null)
            {
                Session["accname"] = null;
                return RedirectToAction("Login", "Account");
            }
            else
            {
                ViewBag.Thang = id;
                ViewBag.doanhthu = aDB.TinhDoanhThuTheoThangNam(Int32.Parse(id), DateTime.Now.Year).ToString("#,##0");
                var model = aDB.LayHoaDonTheoThang(id);
                return View(model);
            }
        }
        [HandleError]
        public ActionResult DoanhThuNam()
        {

            if (Session["accname"] == null)
            {
                Session["accname"] = null;
                return RedirectToAction("Login", "Account");
            }
            else
            {
                return View();
            }
        }      
    }
}

Areas/Administrator/Views/ThongKe/DoanhThuCacThang.cshtml
@model IEnumerable<WatchShop.Areas.Administrator.Models.HoaDon>

@{
    ViewBag.Title = "Doanh Thu Tháng";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

@{
    DateTime dt = new DateTime();
    dt = DateTime.Now;
    int yy = dt.Year;
    WatchShop.Areas.Administrator.AdminDB adB = new WatchShop.Areas.Administrator.AdminDB();
}
<meta charset="utf-8">
<h2>Doanh Thu Tháng @ViewBag.Thang Năm @DateTime.Now.Year</h2>
<hr />
<div>
    <div class="panel panel-default">
        <div class="panel-body" style="width:100%;height:500px;overflow:auto;">
            <div class="table-responsive table-bordered">
                <table class="table">
                    <thead>
                        <tr style="background-color:#eeeeee">
                            <th>#</th>
                            <th>Ngày tạo</th>
                            <th>Tổng cộng</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 0;
                        }
                        @foreach (var item in Model)
                        {
                            i++;
                            <tr>
                                <td>@item.MaHD</td>
                                <td>@item.NgayTao</td>
                                <td>@item.Total.ToString("#,##0") VNĐ</td>
                                <td>
                                    <a href="@Url.Action("Details", "HoaDon",new { id = item.MaHD })" target="_blank"><i class="fa fa-list-alt fa-fw"></i> Xem chi tiết</a>
                                </td>
                            </tr>

                        }
                    </tbody>
                </table>

            </div>
            <div style="position:relative;left: 570px;top:20px;border-bottom:5px solid #a09d9c;width:320px;">
                <strong>TỔNG DOANH THU: </strong>
                <strong style="margin-left: 50px;">@ViewBag.doanhthu VNĐ</strong>
            </div>
            <a href="@Url.Action("DoanhThuNam", "ThongKe")"><i class="fa fa-backward"></i> Quay lại</a>
            <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->

    </div>
    <!-- /.panel -->

</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Areas/Administrator/Views/ThongKe/DoanhThuNam.cshtml
@{
    ViewBag.Title = "Doanh thu năm";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

@{
    WatchShop.Areas.Administrator.AdminDB aDB = new WatchShop.Areas.Administrator.AdminDB();
}

<h2>Doanh thu năm @DateTime.Now.Year</h2>
<script>
    var thang1 =@aDB.TinhDoanhThuTheoThangNam(1,DateTime.Now.Year);
   
    var thang2 =@aDB.TinhDoanhThuTheoThangNam(2,DateTime.Now.Year);
    
    var thang3 =@aDB.TinhDoanhThuTheoThangNam(3,DateTime.Now.Year);
     
    var thang4 =@aDB.TinhDoanhThuTheoThangNam(4,DateTime.Now.Year);
     
    var thang5 =@aDB.TinhDoanhThuTheoThangNam(5,DateTime.Now.Year);
   
    var thang6 =@aDB.TinhDoanhThuTheoThangNam(6,DateTime.Now.Year);
    
    var thang7 =@aDB.TinhDoanhThuTheoThangNam(7,DateTime.Now.Year);
     
    var thang8 =@aDB.TinhDoanhThuTheoThangNam(8,DateTime.Now.Year);
    
    var thang9 =@aDB.TinhDoanhThuTheoThangNam(9,DateTime.Now.Year);
    
    var thang10 =@aDB.TinhDoanhThuTheoThangNam(10,DateTime.Now.Year);
     
    var thang11 =@aDB.TinhDoanhThuTheoThangNam(11,DateTime.Now.Year);
   
    var thang12 =@aDB.TinhDoanhThuTheoThangNam(12,DateTime.Now.Year);

    window.onload = function () {
        var chart = new CanvasJS.Chart("chartContainer", {
            animationEnabled: true,
            theme: "light2", 
            axisY: {
                title: "Đơn vị: VNĐ"
            },
            data: [{
                type: "column",
                dataPoints: [
                    { y: thang1, label: "Tháng 1" },
                    { y: thang2, label: "Tháng 2" },
                    { y: thang3, label: "Tháng 3" },
                    { y: thang4, label: "Tháng 4" },
                    { y: thang5, label: "Tháng 5" },
                    { y: thang6, label: "Tháng 6" },
                    { y: thang7, label: "Tháng 7" },
                    { y: thang8, label: "Tháng 8" },
                    { y: thang9, label: "Tháng 9" },
                    { y: thang10, label: "Tháng 10" },
                    { y: thang11, label: "Tháng 11" },
                    { y: thang12, label: "Tháng 12" }
                ]
            }]
        });
        chart.render();

    }
</script>
<div id="chartContainer" style="height: 370px; width: 100%;margin-top:50px;"></div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<a href="@Url.Action("Index", "ThongKe")"><i class="fa fa-backward"></i> Quay lại</a>
<div style="position:absolute;left:165px;bottom:0px;font-size:20px;">
    <a href="@Url.Action("DoanhThuCacThang", "ThongKe", new { id=1})"><i class="fa fa-info"></i></a>
</div>
<div style="position:absolute;left:300px;bottom:0px;font-size:20px;">
    <a href="@Url.Action("DoanhThuCacThang", "ThongKe", new { id=2})"><i class="fa fa-info"></i></a>
</div>
<div style="position:absolute;left:420px;bottom:0px;font-size:20px;">
    <a href="@Url.Action("DoanhThuCacThang", "ThongKe", new { id=3})"><i class="fa fa-info"></i></a>
</div>
<div style="position:absolute;left:540px;bottom:0px;font-size:20px;">
    <a href="@Url.Action("DoanhThuCacThang", "ThongKe", new { id=4})"><i class="fa fa-info"></i></a>
</div>
<div style="position:absolute;left:660px;bottom:0px;font-size:20px;">
    <a href="@Url.Action("DoanhThuCacThang", "ThongKe", new { id=5})"><i class="fa fa-info"></i></a>
</div>
<div style="position:absolute;left:790px;bottom:0px;font-size:20px;">
    <a href="@Url.Action("DoanhThuCacThang", "ThongKe", new { id=6})"><i class="fa fa-info"></i></a>
</div>
<div style="position:absolute;left:910px;bottom:0px;font-size:20px;">
    <a href="@Url.Action("DoanhThuCacThang", "ThongKe", new { id=7})"><i class="fa fa-info"></i></a>
</div>
<div style="position:absolute;left:1030px;bottom:0px;font-size:20px;">
    <a href="@Url.Action("DoanhThuCacThang", "ThongKe", new { id=8})"><i class="fa fa-info"></i></a>
</div>
<div style="position:absolute;left:1160px;bottom:0px;font-size:20px;">
    <a href="@Url.Action("DoanhThuCacThang", "ThongKe", new { id=9})"><i class="fa fa-info"></i></a>
</div>
<div style="position:absolute;left:1280px;bottom:0px;font-size:20px;">
    <a href="@Url.Action("DoanhThuCacThang", "ThongKe", new { id=10})"><i class="fa fa-info"></i></a>
</div>
<div style="position:absolute;left:1400px;bottom:0px;font-size:20px;">
    <a href="@Url.Action("DoanhThuCacThang", "ThongKe",new { id=11})"><i class="fa fa-info"></i></a>
</div>
<div style="position:absolute;left:1520px;bottom:0px;font-size:20px;">
    <a href="@Url.Action("DoanhThuCacThang", "ThongKe",new { id=12})"><i class="fa fa-info"></i></a>
</div>

Areas/Administrator/Views/ThongKe/DoanhThuThangNam.cshtml
@model IEnumerable<WatchShop.Areas.Administrator.Models.HoaDon>

@{
    ViewBag.Title = "Doanh Thu Thang Nam";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}

@{
    DateTime value = new DateTime();
    value = DateTime.Now;
    int mm = value.Month;
    int yy = value.Year;
    WatchShop.Areas.Administrator.AdminDB adB = new WatchShop.Areas.Administrator.AdminDB();
   
}
<meta charset="utf-8">
<h2 >Doanh Thu Tháng @mm Năm @yy</h2>
<hr/>
<div>   
    <div class="panel panel-default">
        <div class="panel-body" style="width:100%;height:500px;overflow:auto;">
            <div class="table-responsive table-bordered">
                <table class="table">
                    <thead>
                        <tr style="background-color:#eeeeee">
                            <th>#</th>
                            <th>Ngày tạo</th>
                            <th>Tổng cộng</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 0;
                        }
                        @foreach (var item in Model)
                        {
                            i++;
                            <tr>
                                <td>@item.MaHD</td>
                                <td>@item.NgayTao</td>
                                <td>@item.Total.ToString("#,##0") VNĐ</td>
                                <td>
                                    <a href="@Url.Action("Details", "HoaDon",new { id = item.MaHD })" target="_blank"><i class="fa fa-list-alt fa-fw"></i> Xem chi tiết</a>
                                </td>
                            </tr>

                        }
                    </tbody>
                </table>

            </div>
            <div style="position:relative;left: 570px;top:20px;border-bottom:5px solid #a09d9c;width:320px;">
                <strong>TỔNG DOANH THU: </strong>
                <strong style="margin-left: 50px;">@adB.TinhDoanhThuTheoThangNam(mm, yy).ToString("#,##0") VNĐ</strong>
            </div>
            <a href="@Url.Action("Index", "ThongKe")"><i class="fa fa-backward"></i> Quay lại</a>
            <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->

    </div>
    <!-- /.panel -->

</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Areas/Administrator/Views/ThongKe/Index.cshtml
@{
    ViewBag.Title = "Thống kê";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}
@using System;
@using System.Web.Mvc;

    <h2>Thống kê</h2><a href="@Url.Action("Index", "ThongKe")"><span class="fa fa-refresh"> Làm mới</span></a>

                     <div class="row" style="margin-top:20px;">
                         <div class="col-lg-3 col-md-6">
                             <div class="panel panel-strong-green">
                                 <div class="panel-heading">
                                     <div class="row">
                                         <div class="col-xs-3">
                                             <i class="fa fa-dollar" style="font-size:70px"></i>
                                         </div>
                                         @{
                                             DateTime value = new DateTime();
                                             value = DateTime.Now;
                                             int mm = value.Month;
                                             int yy = value.Year;
                                         }
                                         <div class="col-xs-9 text-right">
                                             <div>DOANH THU NĂM @yy</div>
                                             <div class="huge">@ViewBag.DoanhThu</div>
                                         </div>
                                     </div>
                                 </div>
                                 <a href="@Url.Action("DoanhThuNam", "ThongKe")">
                                     <div class="panel-footer">
                                         <span class="pull-left">View Details</span>
                                         <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                         <div class="clearfix"></div>
                                     </div>
                                 </a>
                             </div>
                         </div>
                         <div class="col-lg-3 col-md-6">
                             <div class="panel panel-green">
                                 <div class="panel-heading">
                                     <div class="row">
                                         <div class="col-xs-3">
                                             <i class="fa fa-dollar" style="font-size:70px"></i>
                                         </div>
                                         <div class="col-xs-9 text-right">
                                             <div>DOANH THU THÁNG @mm NĂM @yy<i></i></div>
                                             <div class="huge">@ViewBag.DoanhThuThangNam</div>
                                         </div>
                                     </div>
                                 </div>
                                 <a href="@Url.Action("DoanhThuThangNam", "ThongKe")">
                                     <div class="panel-footer">
                                         <span class="pull-left">View Details</span>
                                         <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                         <div class="clearfix"></div>
                                     </div>
                                 </a>
                             </div>
                         </div>
                         <div class="col-lg-3 col-md-6">
                             <div class="panel panel-primary">
                                 <div class="panel-heading">
                                     <div class="row">
                                         <div class="col-xs-3">
                                             <i class="fa fa-calendar-check-o" style="font-size:70px"></i>
                                         </div>
                                         <div class="col-xs-9 text-right">
                                             <div>HÓA ĐƠN ĐÃ HOÀN TẤT</div>
                                             <div class="huge">@ViewBag.HoaDonDaHoanTat</div>
                                         </div>
                                     </div>
                                 </div>
                                 <a href="@Url.Action("Index4", "HoaDon")">
                                     <div class="panel-footer">
                                         <span class="pull-left">View Details</span>
                                         <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                         <div class="clearfix"></div>
                                     </div>
                                 </a>
                             </div>
                         </div>

                         <div class="col-lg-3 col-md-6">
                             <div class="panel panel-yellow">
                                 <div class="panel-heading">
                                     <div class="row">
                                         <div class="col-xs-3">
                                             <i class="fa fa-calendar-o " style="font-size:70px"></i>
                                         </div>
                                         <div class="col-xs-9 text-right">
                                             <div>HÓA ĐƠN CHỜ XÁC NHẬN</div>
                                             <div class="huge">@ViewBag.HoaDonChoXacNhan</div>
                                         </div>
                                     </div>
                                 </div>
                                 <a href="@Url.Action("Index", "HoaDon")">
                                     <div class="panel-footer">
                                         <span class="pull-left">View Details</span>
                                         <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                         <div class="clearfix"></div>
                                     </div>
                                 </a>
                             </div>
                         </div>
                         <div class="col-lg-3 col-md-6">
                             <div class="panel panel-purple">
                                 <div class="panel-heading">
                                     <div class="row">
                                         <div class="col-xs-3">
                                             <i class="fa fa-calendar-plus-o" style="font-size:70px"></i>
                                         </div>
                                         <div class="col-xs-9 text-right">
                                             <div>HÓA ĐƠN ĐÃ XÁC NHẬN</div>
                                             <div class="huge">@ViewBag.HoaDonDaXacNhan</div>
                                         </div>
                                     </div>
                                 </div>
                                 <a href="@Url.Action("Index2", "HoaDon")">
                                     <div class="panel-footer">
                                         <span class="pull-left">View Details</span>
                                         <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                         <div class="clearfix"></div>
                                     </div>
                                 </a>
                             </div>
                         </div>
                         <div class="col-lg-3 col-md-6">
                             <div class="panel panel-red">
                                 <div class="panel-heading">
                                     <div class="row">
                                         <div class="col-xs-3">
                                             <i class="fa fa-motorcycle" style="font-size:70px"></i>
                                         </div>
                                         <div class="col-xs-9 text-right">
                                             <div>HÓA ĐƠN ĐANG GIAO</div>
                                             <div class="huge">@ViewBag.HoaDonDangGiao</div>
                                         </div>
                                     </div>
                                 </div>
                                 <a href="@Url.Action("Index3", "HoaDon")">
                                     <div class="panel-footer">
                                         <span class="pull-left">View Details</span>
                                         <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                         <div class="clearfix"></div>
                                     </div>
                                 </a>
                             </div>
                         </div>
                         <div class="col-lg-3 col-md-6">
                             <div class="panel panel-pink">
                                 <div class="panel-heading">
                                     <div class="row">
                                         <div class="col-xs-3">
                                             <i class="fa fa-shopping-cart" style="font-size:70px"></i>
                                         </div>
                                         <div class="col-xs-9 text-right">
                                             <div>SẢN PHẨM HẾT HÀNG</div>
                                             <div class="huge">@ViewBag.SanPhamHetHang</div>
                                         </div>
                                     </div>
                                 </div>
                                 <a href="@Url.Action("Index2", "SanPham")">
                                     <div class="panel-footer">
                                         <span class="pull-left">View Details</span>
                                         <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                         <div class="clearfix"></div>
                                     </div>
                                 </a>
                             </div>
                         </div>
                         <div class="col-lg-3 col-md-6">
                             <div class="panel panel-light-blue">
                                 <div class="panel-heading">
                                     <div class="row">
                                         <div class="col-xs-3">
                                             <i class="fa fa-users" style="font-size:70px"></i>
                                         </div>
                                         <div class="col-xs-9 text-right">
                                             <div>KHÁCH HÀNG MỚI</div>
                                             <div class="huge">@ViewBag.NewCus</div>
                                         </div>
                                     </div>
                                 </div>
                                 <a href="@Url.Action("Index", "KhachHang")">
                                     <div class="panel-footer">
                                         <span class="pull-left">View Details</span>
                                         <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                         <div class="clearfix"></div>
                                     </div>
                                 </a>
                             </div>
                         </div>

                     </div>