Areas/Shopper/Controllers/GioHangController.cs
using WatchShop.Areas.Shopper.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WatchShop.Areas.Shopper.Controllers
{
    public class GioHangController : Controller
    {
        UserContext db = new UserContext();

        // GET: Shopper/GioHang
        public ActionResult Index()
        {
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            return View(giohang);

        }
        public ActionResult ThemVaoGio(int SanPhamID)
        {
            if (Session["giohang"] == null) // Nếu giỏ hàng chưa được khởi tạo
            {
                Session["giohang"] = new List<CartItem>();  // Khởi tạo Session["giohang"] là 1 List<CartItem>
            }

            List<CartItem> giohang = Session["giohang"] as List<CartItem>;  // Gán qua biến giohang dễ code

            // Kiểm tra xem sản phẩm khách đang chọn đã có trong giỏ hàng chưa

            if (giohang.FirstOrDefault(m => m.SanPhamID == SanPhamID) == null) // ko co sp nay trong gio hang
            {
                Models.SanPham sp = db.SanPhams.Find(SanPhamID);  // tim sp theo sanPhamID
                
                CartItem newItem = new CartItem()
                {
                    SanPhamID = SanPhamID,
                    TenSanPham = sp.TenSP,
                    SoLuong = 1,
                    soluongmax = (int)sp.SoLuongSP,
                    Hinh = sp.HinhAnh,
                    DonGia = (sp.Gia - (sp.Gia * sp.Discount)/100)

                };  // Tạo ra 1 CartItem mới

                giohang.Add(newItem);  // Thêm CartItem vào giỏ 
            }
            else
            {
                // Nếu sản phẩm khách chọn đã có trong giỏ hàng thì không thêm vào giỏ nữa mà tăng số lượng lên.
                CartItem cardItem = giohang.FirstOrDefault(m => m.SanPhamID == SanPhamID);
                cardItem.SoLuong++;
            }

            // Action này sẽ chuyển hướng về trang chi tiết sp khi khách hàng đặt vào giỏ thành công. Bạn có thể chuyển về chính trang khách hàng vừa đứng bằng lệnh return Redirect(Request.UrlReferrer.ToString()); nếu muốn.
            return Redirect(Request.UrlReferrer.ToString());
        }
        //Sửa số lượng
        public ActionResult SuaSoLuong(int SanPhamID, int soluongmoi)
        {
            // tìm carditem muon sua
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            CartItem itemSua = giohang.FirstOrDefault(m => m.SanPhamID.Equals(SanPhamID));
            if (itemSua != null)
            {
                if (soluongmoi < 1 || soluongmoi > 100)// soluongmoi> select soluongSP from SanPham where MaSP=SanPhamID// dung function() return soluongSP
                {

                }
                else
                {
                    @ViewBag.GioError = "";
                    itemSua.SoLuong = soluongmoi;
                }
            }
            return RedirectToAction("Index");

        }
        //Xoá khỏi giỏ
        public ActionResult XoaKhoiGio(int SanPhamID)
        {
            List<CartItem> giohang = Session["giohang"] as List<CartItem>;
            CartItem itemXoa = giohang.FirstOrDefault(m => m.SanPhamID.Equals(SanPhamID));
            if (itemXoa != null)
            {
                giohang.Remove(itemXoa);
            }
            return RedirectToAction("Index");
        }
    }
}

Areas/Shopper/Views/GioHang/Index.cshtml
@model List<WatchShop.Areas.Shopper.Models.CartItem>
@{
    ViewBag.Title = "Giỏ hàng của bạn";
    Layout = "~/Areas/Shopper/Views/Shared/_LayoutShop.cshtml";
}

@{
    WatchShop.Repository.ProductDAO proDAO = new WatchShop.Repository.ProductDAO();
    WatchShop.Areas.Shopper.Models.SanPham dbp = new WatchShop.Areas.Shopper.Models.SanPham();
}
<div class="container">
    @if (Model == null || Model.Count == 0)
    {
        <div class="spec ">
            <h3>Giỏ hàng</h3>

        </div>
        <p class="text-info text-center" style="font-size:25px;">
            Giỏ hàng của bạn trống!
        </p>
    }
    else
    {
        <div class="spec ">
            <h3>Giỏ hàng</h3>

        </div>
        decimal total = 0;
        int i = 0;
        <div class="row">
            <div class="col-sm-12">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <tr>
                            <th>Hình</th>
                            <th>Tên sản phẩm</th>
                            <th>Số lượng</th>
                            <th>Đơn giá</th>
                            <th>Thành tiền</th>
                            <th></th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="text-center"><img src="@item.Hinh" width="70" height="60" /> </td>
                                <td><a target="_blank" href="@Url.Action("ChiTietSanPham", "SanPham", new { id = item.SanPhamID })" style="font-size:medium;"> @item.TenSanPham </a> </td>
                                <td>                                   
                                    <form id="formSoluong_@i" action="@Url.Action("SuaSoLuong","GioHang")" method="get">
                                        <input type="hidden" name="SanPhamID" value="@item.SanPhamID" />
                                        <input class="col-lg-4" style="height:30px;width:80px;" type="number" min="1" max="@item.soluongmax" name="soluongmoi" value="@item.SoLuong" onchange="$('#formSoluong_@i').submit();" />
                                    </form>
                                </td>
                                <td> @item.DonGia.ToString("#,##0") VNĐ </td>
                                <td> @item.ThanhTien.ToString("#,##0") VNĐ </td>

                                <td> <a href="@Url.Action("XoaKhoiGio",new { SanPhamID = item.SanPhamID})" onclick="return confirm('Bạn có chắc muốn xóa sản phẩm này?');" class="btn btn-danger btn-sm">Xóa</a> </td>
                            </tr>
                            i++;
                            total += @item.ThanhTien;
                        }
                        <tr>
                            <td></td>
                            <td class="text-right"></td>
                            <td></td>
                            <td class="text-right">Tổng thành tiền:</td>
                            <td style="font-size:large;">@total.ToString("#,##0") VNĐ </td>
                            <td><a href="@Url.Action("Index", "ThanhToan")" role="button" class="btn btn-success" style="background-color:#379683;border:none">Thanh toán</a></td>
                        </tr>
                    </table>
                </div>

            </div>

        </div>
    }
</div>